import Layout from '../components/layout'
import Sidebar from '../components/sidebar'

import React from "react";

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://drom.machine.com">Drom Machine</a>
        </h1>

        <p className={styles.description}>
          An Lucid Dream App{' '}
          <code className={styles.code}> using React.js/Unreal.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Features &rarr;</h2>
            <p>
              See the planned features layed out here.
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>
              About me page goes here.
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Scene Playlist &rarr;</h2>
            <p>
              Still picturesque photos with ambiance.
            </p>
          </a>

          <a
            href="/journeys"
            className={styles.card}
          >
            <h2>Journeys &rarr;</h2>
            <p>
              360 video playlists along with ambiance.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Drom Digital" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


export function getStaticProps() {

  return {

    props: {

      data: {

        scenes: [{ title: "Abandoned Apartment"}],

      },

    },

  };

}


// export function Index() {
//   return (
    
//     <section>
//       <h2>Layout Example (Index)</h2>
      
//     </section>
//   )
// }


// Index.getLayout = function getLayout(page) {
//   return (
//     <Layout>
//       <Sidebar />
//       {page}
//     </Layout>
//   )
// }